"""empty message

Revision ID: 14b61512ac3b
Revises: e33bd97e207c
Create Date: 2022-08-24 22:15:14.268902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b61512ac3b'
down_revision = 'e33bd97e207c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('display_comments', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'display_comments')
    # ### end Alembic commands ###
